import 'package:flutter/material.dart';

class GameUtils {
  final List<IconData> iconsList = [
  Icons.ac_unit,
  Icons.access_alarm,
  Icons.accessibility,
  Icons.account_balance,
  Icons.adb,
  Icons.airplanemode_active,
  Icons.anchor,
  Icons.android,
  Icons.api,
  Icons.archive,
  Icons.arrow_forward,
  Icons.assistant,
  Icons.audiotrack,
  Icons.baby_changing_station,
  Icons.backup,
  Icons.bakery_dining,
  Icons.beach_access,
  Icons.bed,
  Icons.bike_scooter,
  Icons.blender,
  Icons.book,
  Icons.brightness_5,
  Icons.brush,
  Icons.bug_report,
  Icons.cake,
  Icons.camera,
  Icons.car_rental,
  Icons.casino,
  Icons.catching_pokemon,
  Icons.cell_wifi,
  Icons.chair,
  Icons.coffee,
  Icons.computer,
  Icons.construction,
  Icons.coronavirus,
  Icons.dangerous,
  Icons.deck,
  Icons.directions_boat,
  Icons.directions_bike,
  Icons.directions_bus,
  Icons.directions_car,
  Icons.emoji_emotions,
  Icons.emoji_food_beverage,
  Icons.engineering,
  Icons.face,
  Icons.fastfood,
  Icons.favorite,
  Icons.fitness_center,
  Icons.flight,
  Icons.gamepad,
  Icons.handyman,
  Icons.headphones,
  Icons.health_and_safety,
  Icons.home,
  Icons.icecream,
  Icons.kayaking,
  Icons.keyboard,
  Icons.light_mode,
  Icons.local_florist,
  Icons.local_grocery_store,
  Icons.local_hospital,
  Icons.local_pizza,
  Icons.luggage,
  Icons.music_note,
  Icons.nature,
  Icons.nightlife,
  Icons.palette,
  Icons.pets,
  Icons.phone_android,
  Icons.pool,
  Icons.rocket_launch,
  Icons.school,
  Icons.snowboarding,
  Icons.spa,
  Icons.sports_basketball,
  Icons.surfing,
  Icons.theater_comedy,
  Icons.thumb_up,
  Icons.umbrella,
  Icons.videogame_asset,
  Icons.wb_sunny,
  Icons.work,
];

final List<Color> colorsList = [
  Colors.red,
  Colors.green,
  Colors.blue,
  Colors.orange,
  Colors.purple,
  Colors.pink,
  Colors.teal,
  Colors.amber,
  Colors.indigo,
  Colors.brown,
  Colors.cyan,
  Colors.deepOrange,
  Colors.deepPurple,
  Colors.lightBlue,
  Colors.lightGreen,
  Colors.lime,
  Colors.yellow,
  Colors.grey,
  Colors.blueGrey,
  Colors.black,
  Color(0xFF6A1B9A), // custom roxo escuro
  Color(0xFF00897B), // custom verde água
  Color(0xFF546E7A), // custom cinza azulado
  Color(0xFFEF5350), // custom vermelho suave
  Color(0xFF26C6DA), // custom azul claro
  Color(0xFFFFA726), // custom laranja claro
  Color(0xFF66BB6A), // custom verde médio
  Color(0xFF42A5F5), // custom azul médio
];


}